

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
IF (not EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Version'))
BEGIN
	CREATE TABLE [dbo].[Version](
		[Version_Id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
		[Version_TimeStamp] [varchar](64) NOT NULL,	
		[Version_SchemaType] [int] NOT NULL,
		[Version_DateApplied] [datetime] NOT NULL,
	 CONSTRAINT [PK_Version] PRIMARY KEY CLUSTERED 
	(
		[Version_Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END
GO

SET ANSI_PADDING OFF
GO
IF not EXISTS (SELECT name FROM sysindexes WHERE name = 'IX_Timestamp') 
BEGIN
	CREATE UNIQUE NONCLUSTERED INDEX [IX_Timestamp] ON [dbo].[Version] 
	(
		[Version_Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
END

GO
